### ISSUE TITLE
[Feat] UI 비율 확인 후 수정

### ISSUE THREAD

**Issue by singhae** [HGU-iOS-Study-Group/Pomodoro#211]
- [ ] 각 화면 비율 확인 후 수정

<img width="308" alt="스크린샷 2024-03-31 오후 5 55 55" src="https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/90087719/167a1011-7292-45aa-a322-b0016c8f4552">
<img width="301" alt="스크린샷 2024-03-31 오후 5 56 23" src="https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/90087719/cff2d27a-a2c4-4b6a-9cb2-aace5f26f02d">

(피그마 화면 그대로 캡쳐했는데 둘이 이미지 크기 차이가 좀 있는 듯 합니다.)

**Comment by jeonyeohun** [comment]
무슨 작업인지 잘 이해가 안됩니다. 내용 추가부탁드려요.
