### ISSUE TITLE
[Bug][집중시작] 뽀모도로 시작 > 중단 > 앱 종료 > 앱 실행시 이전 설정 시간으로 뽀모도로가 시작되는 현상

### ISSUE THREAD

**Issue by jeonyeohun** [HGU-iOS-Study-Group/Pomodoro#259]
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/46087477/5f6ae923-d1cc-4f18-8418-35581cb26432

**Comment by hgkim00** [comment]
내 핸드폰에서는 잘 작동해서 클로즈.
