### ISSUE TITLE
[Bug][설정] 데이터 초기화를 실행해도 대시보드 데이터가 남아있는 현상

### ISSUE THREAD

**Issue by jeonyeohun** [HGU-iOS-Study-Group/Pomodoro#269]
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/46087477/35002a34-eb09-4c0d-9bc9-04c19356af7a

**Comment by haram22** [comment]
여기서 다른 탭 선택하면 초기화 되는데 대시보드 화면에 들어갈 때마다 새로고침처럼 데이터를 다시 불러오도록 해야할까요?
지금은 탭 선택 시 렘에서 데이터 불러오도록 되어 있습니다 !

**Comment by jeonyeohun** [comment]
@haram22 님 대시보드 처음 들어갈때는 새로고침 하는게 맞는 것 같아요~
