### ISSUE TITLE
[Bug][집중시작] 뽀모도로 시작 후 백그라운드 진입 > 일정 시간 흐른 후 다시 앱에 돌아왔을 때 시간이 백그라운드 진입 전 시간에서 시작되는 현상

### ISSUE THREAD

**Issue by jeonyeohun** [HGU-iOS-Study-Group/Pomodoro#272]
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/46087477/186f7136-5061-4c6a-82e6-275946850ea8

**Comment by hgkim00** [comment]
내 핸드폰에서는 잘 작동해서 일단 클로즈.
