### ISSUE TITLE
[Bug][태그설정] 앱 삭제 후 가장 처음 빌드 후 태그 생성한 뒤 태그 선택 시 선택 태그가 홈에 보이지 않는 현상

### ISSUE THREAD

**Issue by haram22** [HGU-iOS-Study-Group/Pomodoro#273]
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/97924765/4db171d0-ee8f-43fd-b90e-c4dab5859417

**Comment by jeonyeohun** [comment]
https://github.com/HGU-iOS-Study-Group/Pomodoro/issues/287 duplicated
